Failed to execute code at iteration 6: Traceback (most recent call last):
  File "/home/anyaji/grounded-edit/playground/data/business_slide_1/iter_6/gpt-4o/code.py", line 29, in <module>
    logo_shape = slide.shapes.add_picture(logo_icon_path, Inches(3), Inches(2), Inches(10), Inches(5))
  File "/home/anyaji/anaconda3/envs/edits/lib/python3.10/site-packages/pptx/shapes/shapetree.py", line 370, in add_picture
    image_part, rId = self.part.get_or_add_image_part(image_file)
  File "/home/anyaji/anaconda3/envs/edits/lib/python3.10/site-packages/pptx/parts/slide.py", line 50, in get_or_add_image_part
    image_part = self._package.get_or_add_image_part(image_file)
  File "/home/anyaji/anaconda3/envs/edits/lib/python3.10/site-packages/pptx/package.py", line 38, in get_or_add_image_part
    return self._image_parts.get_or_add_image_part(image_file)
  File "/home/anyaji/anaconda3/envs/edits/lib/python3.10/site-packages/pptx/package.py", line 153, in get_or_add_image_part
    image = Image.from_file(image_file)
  File "/home/anyaji/anaconda3/envs/edits/lib/python3.10/site-packages/pptx/parts/image.py", line 163, in from_file
    with open(image_file, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '../../media/image_1_solid_white.jpg'
