Failed to execute code at iteration 2: Traceback (most recent call last):
  File "/home/anyaji/anaconda3/envs/edits/lib/python3.10/site-packages/PIL/JpegImagePlugin.py", line 639, in _save
    rawmode = RAWMODE[im.mode]
KeyError: 'RGBA'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/anyaji/grounded-edit/playground/data/business_slide_13/iter_2/gpt-4o/code.py", line 20, in <module>
    blurred_image.save(blurred_image_path)
  File "/home/anyaji/anaconda3/envs/edits/lib/python3.10/site-packages/PIL/Image.py", line 2568, in save
    save_handler(self, fp, filename)
  File "/home/anyaji/anaconda3/envs/edits/lib/python3.10/site-packages/PIL/JpegImagePlugin.py", line 642, in _save
    raise OSError(msg) from e
OSError: cannot write mode RGBA as JPEG
