Failed to execute code for edit 3: Traceback (most recent call last):
  File "/home/anyaji/anaconda3/envs/edits/lib/python3.10/site-packages/pptx/opc/serialized.py", line 84, in _write
    self._write_content_types_stream(phys_writer)
  File "/home/anyaji/anaconda3/envs/edits/lib/python3.10/site-packages/pptx/opc/serialized.py", line 94, in _write_content_types_stream
    phys_writer.write(
  File "/home/anyaji/anaconda3/envs/edits/lib/python3.10/site-packages/pptx/opc/serialized.py", line 236, in write
    self._zipf.writestr(pack_uri.membername, blob)
  File "/home/anyaji/anaconda3/envs/edits/lib/python3.10/site-packages/pptx/util.py", line 191, in __get__
    value = self._fget(obj)
  File "/home/anyaji/anaconda3/envs/edits/lib/python3.10/site-packages/pptx/opc/serialized.py", line 241, in _zipf
    return zipfile.ZipFile(
  File "/home/anyaji/anaconda3/envs/edits/lib/python3.10/zipfile.py", line 1254, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: 'examples/environment/slide_3/gpt_4o.pptx'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/anyaji/grounded-edit/playground/data/environment_slide_3/gpt-4o/edit_3/code.py", line 56, in <module>
    presentation.save(save_path)
  File "/home/anyaji/anaconda3/envs/edits/lib/python3.10/site-packages/pptx/presentation.py", line 50, in save
    self.part.save(file)
  File "/home/anyaji/anaconda3/envs/edits/lib/python3.10/site-packages/pptx/parts/presentation.py", line 112, in save
    self.package.save(path_or_stream)
  File "/home/anyaji/anaconda3/envs/edits/lib/python3.10/site-packages/pptx/opc/package.py", line 156, in save
    PackageWriter.write(pkg_file, self._rels, tuple(self.iter_parts()))
  File "/home/anyaji/anaconda3/envs/edits/lib/python3.10/site-packages/pptx/opc/serialized.py", line 79, in write
    cls(pkg_file, pkg_rels, parts)._write()
  File "/home/anyaji/anaconda3/envs/edits/lib/python3.10/site-packages/pptx/opc/serialized.py", line 83, in _write
    with _PhysPkgWriter.factory(self._pkg_file) as phys_writer:
  File "/home/anyaji/anaconda3/envs/edits/lib/python3.10/site-packages/pptx/opc/serialized.py", line 232, in __exit__
    self._zipf.close()
  File "/home/anyaji/anaconda3/envs/edits/lib/python3.10/site-packages/pptx/util.py", line 191, in __get__
    value = self._fget(obj)
  File "/home/anyaji/anaconda3/envs/edits/lib/python3.10/site-packages/pptx/opc/serialized.py", line 241, in _zipf
    return zipfile.ZipFile(
  File "/home/anyaji/anaconda3/envs/edits/lib/python3.10/zipfile.py", line 1254, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: 'examples/environment/slide_3/gpt_4o.pptx'
